### ISSUE TITLE
Trouble getting commands to run

### ISSUE THREAD

**Issue by profucius** [hassanaziz0012/spotify-downloader#1]
Hi, I'm trying to get your script running on my machine, and am having some issues. I am only novice with docker so please forgive my ignorance.

I am using Windows running Docker Desktop. I first cloned the repo to my host OS, then ran the docker commands to build and run it. Everything seemed to go fine.

I then tried running the download commands in the Usage section of your readme, but I cant seem to get it to work. I see the download commands use python, so now I'm confused if the downloads go through the host or the docker.

Is the docker self-contained with python and all the tools? Or do I need python installed on the host OS and the commands to be run through the host OS? 

Do I need to keep the cloned repo folder on the host OS in a permanent location, or can I delete it now that the docker is built?

Do the downloading commands need to be run within a host OS command prompt (windows) or within a docker command terminal?

If docker terminal, it's telling me that python cannot be found.

Thanks

**Comment by hassanaziz0012** [comment]
Hey, 

Python is installed in the docker image already, along with all the other dependencies. So, your commands should still work. The only real connection you still have to your host machine is the volume you create for your music folder to store the downloads. That's all mentioned in the instructions. Everything's done in the container. 

Can you show me exactly what error you're getting, and what command you're running, etc? Let's try to figure this out.
