### ISSUE TITLE
Issues loading the script on MacOS

### ISSUE THREAD

**Issue by mpdeboer08** [hassanaziz0012/spotify-downloader#2]
Hello Hassan,

Thanks for your effort in putting this together. I am however encountering errors when installing on Mac. I'm pretty sure the issue is on my end but I have no clue how to go from here... See the code below:

```
MyMachine spotify-downloader % docker run -it -v users/marc/music:/app/music spotify-downloader
Unable to find image 'spotify-downloader:latest' locally
docker: Error response from daemon: Head "https://registry-1.docker.io/v2/library/spotify-downloader/manifests/latest": unauthorized: incorrect username or password.
See 'docker run --help'.

```

Thanks!

**Comment by hassanaziz0012** [comment]
Hey, 

Looks like it can't find the image locally. You probably forgot to build it. cd into the project directory and run this command:
`docker build -t spotify-downloader .`

Then the run command will work.

Lemme know if you still encounter issues after that. :)
